version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: npm run build && git diff --exit-code
      - run: npm test -- --browsers ChromeHeadless,Firefox
      - run: test -z "$CIRCLE_PULL_REQUEST" && ./node_modules/.bin/codecov
